### ISSUE TITLE
Allow supplying path to .install()

### ISSUE THREAD

**Issue by NickCrews** [zaironjacobs/get-chrome-driver#5]
First of all, I really appreciate this library. I think the API is much better, than similar libs. I love that I can re-install a new version of chromedriver without having to pip reinstall a new version of this lib. And that you explicitly install stuff, not implicitly when you import the library.

I want a oneline install like .install() allows, but I want to be able to specify the path to download to. Can we surface this in the API, and just forward it to the underlying functions? I can write a PR. Would you be open to breaking changes? I also would be interested in streamlining the API more, I think we could make it more focused so there are just a few public functions, each with a larger set of optional args.

**Comment by zaironjacobs** [comment]
> First of all, I really appreciate this library. I think the API is much better, than similar libs. I love that I can re-install a new version of chromedriver without having to pip reinstall a new version of this lib. And that you explicitly install stuff, not implicitly when you import the library.
> 
> I want a oneline install like .install() allows, but I want to be able to specify the path to download to. Can we surface this in the API, and just forward it to the underlying functions? I can write a PR.

Happy to hear that you like this library!
If you write a PR to allow a path specified for .install(), I will merge it.

**Comment by zaironjacobs** [comment]
Optional output_path is now allowed in `.install()`.
