### ISSUE TITLE
Beta Chromedriver download not working 

### ISSUE THREAD

**Issue by nicolettecelli** [zaironjacobs/get-chrome-driver#6]
The ChromeDriver team announced that they're no longer going to upload the drivers to https://chromedriver.chromium.org/
The new site is here https://googlechromelabs.github.io/chrome-for-testing/
It's currently failing if you try to download the beta driver, and will fail eventually for stable after the next chrome release.

Full conversation: https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE

**Comment by zaironjacobs** [comment]
Thanks for the heads-up!

The package has been updated to use the new API.

**Comment by zaironjacobs** [comment]
Thanks for the heads-up!

The package has been updated to use the new API.

**Comment by nicolettecelli** [comment]
@zaironjacobs Thanks!
FYI, line 255 in get_driver.py is failing for beta linux and I think it won't work after next release:
`os.chmod(f"{download_output_path}/chromedriver", 0o755)`

 it looks like the file structure changed in version 115 to include the platform so now it looks like `chromedriver/115.0.5790.13/bin/chromedriver-linux64/chromedriver`

**Comment by zaironjacobs** [comment]
> @zaironjacobs Thanks! FYI, line 255 in get_driver.py is failing for beta linux and I think it won't work after next release: `os.chmod(f"{download_output_path}/chromedriver", 0o755)`
> 
> it looks like the file structure changed in version 115 to include the platform so now it looks like `chromedriver/115.0.5790.13/bin/chromedriver-linux64/chromedriver`

The extracted zip file used to contain just the driver file, now it contains a folder that has the driver file.
I updated the package to check for this as well.
