### ISSUE TITLE
Return downloaded path from install function

### ISSUE THREAD

**Issue by ManishIBM** [zaironjacobs/get-chrome-driver#7]
Hi,
Thanks for developing it, I liked it. I request you to return downloaded path (relative path). Many of the existing libraries return it and if we want to replace, it would be nice to return the path.

**Comment by ManishIBM** [comment]
I created a PR https://github.com/zaironjacobs/get-chrome-driver/pull/8, please have a look.

**Comment by zaironjacobs** [comment]
> I created a PR #8, please have a look.

Your PR has been merged.

**Comment by ManishIBM** [comment]
Thanks!
